name = "MyPkg"
uuid = "3cd6a54d-731d-4dbf-b781-4276fd20a30f"
authors = ["JÃ¼rgen Fuhrmann <juergen-fuhrmann@web.de> and contributors"]
version = "1.1"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
